### ISSUE TITLE
Fast scroll bug on Android 5.1

### ISSUE THREAD

**Issue by percicjan** [AndroidDeveloperLB/ListViewVariants#1]
There is a design bug on Android version 22. Fast scroll indicator looks weird (not like in contacts app).

![screenshot_2015-03-14-15-56-58](https://cloud.githubusercontent.com/assets/5251229/6652374/e83c69e4-ca63-11e4-95d5-528a3680db5a.png)

**Comment by AndroidDeveloperLB** [comment]
This is weird. How do you think the fast scroller should be used on 5.1 ?
Has anything changed in this regard?
Maybe it has something to do with this:
http://developer.android.com/reference/android/widget/AbsListView.html#setFastScrollStyle(int)
?
I can't find how to use this new function.

Anyway, I've now posted about this on StackOverflow, here:
http://stackoverflow.com/q/29053248/878126

Thank you for reporting about this.

**Comment by percicjan** [comment]
The design of the fast scroll hasn't changed in Contacts app on 5.1 so it should be the same I think. 

I haven't seen setFastScrollStyle() yet but is was introduced in 21 so that might not be it.

**Comment by AndroidDeveloperLB** [comment]
@percicjan Yes, I have no idea what's going on. Please let me know if you find out the cause for this, and how to fix it.

**Comment by AndroidDeveloperLB** [comment]
@percicjan I've found why it happens : That's just how it is on Android 5.1 for ListView or any AdapterView.

However, I'm sure it's possible to use this library I've made to mimic how it looks like on the contacts app:
https://github.com/AndroidDeveloperLB/LollipopContactsRecyclerViewFastScroller
