### ISSUE TITLE
Cursor support

### ISSUE THREAD

**Issue by vvsevolodovich** [AndroidDeveloperLB/ListViewVariants#10]
No cursor adapter support, is it planned?

**Comment by AndroidDeveloperLB** [comment]
Sorry, no.
To tell the truth, I've never even used CursorAdapter, other than POCs and demos.

**Comment by vvsevolodovich** [comment]
Well, it seems I have written the support. Do you mind review a pull request if I submit one?

**Comment by AndroidDeveloperLB** [comment]
It seems? :)
You can show it to me if you wish. I will probably learn a few things about it while reading it.
It would also be great if you added a sample, especially if it contains examples of the other classes I've written (yet didn't use in the sample).
