### ISSUE TITLE
change PreferenceActivity to PreferenceFragmentCompat in old project

### ISSUE THREAD

**Issue by neuberfran** [AndroidDeveloperLB/ListViewVariants#14]
Hi,

I need very much your help, even if it is small

I stay taking PreferenceActivity of project links below and I put PreferenceFragmentCompat

http://ryanfx.blogspot.com/2013/06/raspberry-pi-powered-android-controlled.html

https://github.com/ryanfx/GarageAndroid/blob/master/src/com/blogspot/ryanfx/activity/ConfigurationActivity.java

**I have issue of the picture below and this is my project (with issue):**

https://github.com/neuberfran/AlarmController/blob/master/app/src/main/java/com/blogspot/neuberfran/activity/ConfigurationActivity.java

**What about context of the PreferenceFragmentCompat? getActivity() in line 62 in my ConfigurationActivity.java is correct?**

**What I need do to solve my issue?**

![issue111](https://user-images.githubusercontent.com/38701397/59474304-99ad2300-8e1c-11e9-8570-5a7a419e9e36.png)

**Comment by AndroidDeveloperLB** [comment]
This has nothing to do with the library, which I stopped supporting anyway.
You should ask this question on StackOverflow instead.
If you wish, write here a link to the question there.
Please write there a minimal yet working code so that I could understand what is going on.

**Comment by neuberfran** [comment]
https://stackoverflow.com/questions/56555049/how-to-deserialize-number-value-in-firestore-field-and-read-this-inside-de-while

**Comment by AndroidDeveloperLB** [comment]
This doesn't look like the issue you wrote here, of PreferenceActivity  and PreferenceFragmentCompat

**Comment by neuberfran** [comment]
If you Know about this: https://stackoverflow.com/questions/52723661/how-to-open-a-new-preferencefragment-from-current-one-using-the-new-android-x-a then  can help me, more.

**Comment by AndroidDeveloperLB** [comment]
I'm the one who wrote this question, and I already set an answer to be the correct one.

**Comment by neuberfran** [comment]
As you asked I created the topic, hope you can help, at least a little.

https://stackoverflow.com/questions/56858140/transpose-project-with-preferenceactivity-appcompat-v728-0-0-to-preferencefragm.
