### ISSUE TITLE
Sticky Header Issue on Nexus 4

### ISSUE THREAD

**Issue by wizarcane** [AndroidDeveloperLB/ListViewVariants#2]
Hi!

I'm having issues with the sticky headers when the app is deployed and running on a Nexus 4 device (Android OS version 4.0 - 4.3; still testing on later versions). The first sticky header doesn't move/slide which covers other section headers. But this issue doesn't occur in Nexus 4, Android 4.4 and on Samsung Galaxy S3, Android OS version 4.2.

Would you have an idea why this occurs? Hoping to hear from you.
Thank you.

**Comment by AndroidDeveloperLB** [comment]
I'm not sure what's the issue, but I've already tested it on multiple devices (including with Android 4.0-4.3) and on emulators, and it seems to work fine.
Can you reproduce the issue on Android 4.0-4.3 emulators too?

Was the sample problematic, or a modified version of it?

**Comment by wizarcane** [comment]
Oh sorry. Just checked out the latest version and the sample works fine. I'm just not so sure how come that the sliding of sticky headers works on some phones but not on certain versions of Android in Nexus 4. 

Here's a screenshot if it helps. Two sections have passed but the first sticky header here (the '4') didn't move.

![screen shot 2015-04-17 at 3 41 30 pm](https://cloud.githubusercontent.com/assets/8733111/7197857/941d8846-e518-11e4-9f04-2324bfba8b1d.png)

**Comment by AndroidDeveloperLB** [comment]
I don't understand. The issue exists or not?
Also, the code wasn't updated for a very long time.

**Comment by wizarcane** [comment]
The sample doesn't have the issue, but the issue exists on my app. The only difference compared to my app is that I applied styles to the text (and I have no idea how would that affect the moving of sticky header). It works fine on Nexus 4 - Android 4.4 but not on the older OS versions.

**Comment by AndroidDeveloperLB** [comment]
This sounds odd.
Maybe use the sample, and modify it to use your style?
And if the issue occurs, maybe publish it here and it would be possible to
help?
