### ISSUE TITLE
Setting filter doesn't refresh sticky headers

### ISSUE THREAD

**Issue by mikechang1926** [AndroidDeveloperLB/ListViewVariants#8]

**Comment by AndroidDeveloperLB** [comment]
Any code or example video? I don't understand what you mean...

**Comment by Alchemy-Meister** [comment]
I guess he means this. Can't figure out how to make the Pinned Header work properly.
![photo_2016-04-02_20-12-45](https://cloud.githubusercontent.com/assets/5882817/14228271/75ad2be8-f910-11e5-955d-05f114b95ff5.jpg)

**Comment by Alchemy-Meister** [comment]
This is the code I use to filter the adapter.
`@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(R.menu.search_menu, menu);

```
    MenuItem searchItem = menu.findItem(R.id.searchView);
    searchView = (SearchView) searchItem.getActionView();
    searchView.setQueryHint(getResources().getString(R.string.hint));

    SearchManager searchManager = (SearchManager) getSystemService(Context.SEARCH_SERVICE);
    searchView.setSearchableInfo(searchManager.getSearchableInfo(getComponentName()));

    searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener()
    {
        @Override
        public boolean onQueryTextChange(String newText)
        {
            // this is your adapter that will be filtered
            mAdapter.getFilter().filter(newText);
            return true;
        }
        @Override
        public boolean onQueryTextSubmit(String query)
        {
            // this is your adapter that will be filtered
            mAdapter.getFilter().filter(query);
            return true;
        }
    });

    return super.onCreateOptionsMenu(menu);
}`
```

**Comment by AndroidDeveloperLB** [comment]
Did you use "SearchablePinnedHeaderListViewAdapter.java" ?

**Comment by Alchemy-Meister** [comment]
Yes, I just copied your ContactsAdapter from the MainActivity class.

**Comment by AndroidDeveloperLB** [comment]
According to what I've done with this library, I did 2 things, according to the requirements:
1. this (hide the headers when result is filtered) :
   public void performSearch(final String queryText) {
           adapter.getFilter().filter(queryText);
           adapter.setHeaderViewVisible(TextUtils.isEmpty(queryText));
   }
2. or this(after loader finished filtering, just show the filtered result) :
   
   ```
      adapter.setData(filteredResult);
   ```

I think you can also change the way it works. by setting the data that the adapter uses, to be the filtered one when it finishes to filter. Just don't forget to re-build the headers too.

**Comment by AndroidDeveloperLB** [comment]
updated sample to show how to #1
