### ISSUE TITLE
Add cursor adapter supporting

### ISSUE THREAD

**Issue by bartwell** [AndroidDeveloperLB/ListViewVariants#9]
Thank you for great work!

I have a large database and I want to fill ListViewVariants using Cursor. How to implement it?

**Comment by AndroidDeveloperLB** [comment]
To tell you the truth, I've never used CursorAdapter...
The DB was always small enough that a simple query was fine to get the items into a list/array, and I always used a normal BaseAdapter.
If you insist on using CursorAdapter, you probably know better than me about how to use it. I'm sure you will succeed.

**Comment by bartwell** [comment]
Okay, currently I make list without sections. At now I can't understand one thing: why you are using custom SectionIndexer? And why you pass items into SectionIndexer? Just for items sorting? Or something else?
Thank you.

**Comment by AndroidDeveloperLB** [comment]
I don't remember, but I think that it's needed for handling flat-position <-> sectioned-positions conversions.
And that's so that you could access both of them easier and in best efficiency (you need to implement "getPositionForSection" and "getSectionForPosition") .

**Comment by bartwell** [comment]
Thank you for help!

**Comment by AndroidDeveloperLB** [comment]
You're welcomed.
You can also try out my other repos if you wish.
